repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: ["--no-update"]
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt"]
        verbose: true
      - id: poetry-export
        args: ["--with", "dev", "-f", "requirements.txt", "-o", "requirements_dev.txt"]
        verbose: true
  # black - formatting
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  # isort - sorting imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
  # flake8 - linting
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
